# ベースイメージとしてpython:3.8を使用
FROM python:3.8

# 環境変数の設定
ENV PYTHONUNBUFFERED=1
ENV POETRY_VERSION=1.5.0

# コードを配置するディレクトリを作成
RUN mkdir /code

# 作業ディレクトリの設定
WORKDIR /code

# Poetryのインストール
RUN pip install "poetry==$POETRY_VERSION"

# pyproject.tomlとpoetry.lockファイルをコピー
COPY pyproject.toml poetry.lock /code/

# 依存関係のインストール
RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

# "wait-for-it"スクリプトをコピー
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# アプリケーションのソースコードをコピー
COPY . /code/

# Djangoのrunserverを使用してアプリケーションを起動するコマンドに変更
CMD exec /wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:$PORT
